version: '2'
services:
  server:
    build:
      context: ./server
    volumes:
      - ./server/:/usr/app
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
    volumes:
      - ./client/:/usr/app
    depends_on:
      - server
    ports:
      - "3001:3001"